#!/usr/bin/env python3
"""Regenerate the inline panel mascot from the tracked master artwork.

The Decky frontend bundle has no asset pipeline, so the panel carries the
mascot as a data URI compiled into `dist/index.js`. That derivative has to be
reproducible from the master rather than pasted by hand, or the next person to
replace the artwork has no way to rebuild it.

The derivative is deliberately small: a palettised PNG at twice the width it is
drawn at, which is sharp where the QAM is scaled up and costs the bundle a few
kilobytes rather than the master's megabyte.

Requires `ffmpeg` on PATH. This is a development tool; it is not part of
`scripts/qa.py` and never runs during a build.
"""

from __future__ import annotations

from pathlib import Path
import argparse
import base64
import shutil
import subprocess
import tempfile
import textwrap

ROOT = Path(__file__).resolve().parent.parent
MASTER = ROOT / "docs" / "assets" / "hexpaw.png"
MODULE = ROOT / "src" / "assets" / "hexpaw.ts"
# Twice the 112px the panel draws it at. The panel sizes width only, so the
# height follows the artwork's own 2:1 ratio.
WIDTH = 224
# The artwork is three flat colours plus antialiasing, so a small palette is
# visually identical and roughly a third of the bytes.
MAX_COLORS = 48


def _ffmpeg() -> str:
    found = shutil.which("ffmpeg")
    if not found:
        raise SystemExit("ffmpeg is required to rebuild the mascot asset")
    return found


def _run(argv: list[str]) -> None:
    result = subprocess.run(argv, capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(f"ffmpeg failed: {result.stderr.strip()[-2000:]}")


def _derive(ffmpeg: str, master: Path, work: Path) -> bytes:
    palette = work / "palette.png"
    scaled = work / "hexpaw-panel.png"
    _run([
        ffmpeg, "-y", "-loglevel", "error", "-i", str(master),
        "-vf", f"scale={WIDTH}:-1:flags=lanczos,"
               f"palettegen=max_colors={MAX_COLORS}:reserve_transparent=1:stats_mode=full",
        str(palette),
    ])
    _run([
        ffmpeg, "-y", "-loglevel", "error", "-i", str(master), "-i", str(palette),
        "-lavfi", f"[0:v]scale={WIDTH}:-1:flags=lanczos[s];"
                  "[s][1:v]paletteuse=dither=none:alpha_threshold=128",
        "-compression_level", "100", str(scaled),
    ])
    return scaled.read_bytes()


def _module_source(png: bytes) -> str:
    encoded = base64.b64encode(png).decode("ascii")
    body = "\n".join(f'  + "{chunk}"' for chunk in textwrap.wrap(encoded, 100))
    return f'''/**
 * HexPaw, the CE Decky mascot, as an inline data URI.
 *
 * The Decky frontend bundle has no asset pipeline, so the image is carried in
 * the bundle itself rather than fetched from the plugin directory at runtime.
 * This is the {WIDTH}px palettised derivative of `docs/assets/hexpaw.png` - twice
 * the width the panel draws it at, so it stays sharp where the QAM is scaled
 * up, and small enough that inlining it costs a few kilobytes.
 *
 * Generated by `python scripts/build_mascot_asset.py`; do not hand-edit.
 */
export const HEXPAW_DATA_URI =
  "data:image/png;base64,"
{body};

/** Intrinsic aspect ratio of the artwork, so callers size one axis only. */
export const HEXPAW_ASPECT_RATIO = 2;
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="fail if the tracked module does not match the master",
    )
    arguments = parser.parse_args()
    if not MASTER.is_file():
        raise SystemExit(f"master artwork is missing: {MASTER.relative_to(ROOT)}")
    ffmpeg = _ffmpeg()
    with tempfile.TemporaryDirectory() as directory:
        source = _module_source(_derive(ffmpeg, MASTER, Path(directory)))
    if arguments.check:
        current = MODULE.read_text(encoding="utf-8") if MODULE.is_file() else ""
        if current != source:
            raise SystemExit(f"{MODULE.relative_to(ROOT)} is stale: rerun without --check")
        print(f"{MODULE.relative_to(ROOT)} matches {MASTER.relative_to(ROOT)}")
        return
    MODULE.parent.mkdir(parents=True, exist_ok=True)
    MODULE.write_text(source, encoding="utf-8")
    print(f"wrote {MODULE.relative_to(ROOT)} from {MASTER.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
